import "../styles/globals.scss";
import type { AppProps } from "next/app";
import { MantineProvider, Tuple } from "@mantine/core";
import Head from "next/head";

let colors: Record<string, Tuple<string, 10>> = {
	red: [
		"#FAEAEA",
		"#F2C5C5",
		"#EA9F9F",
		"#E17979",
		"#D95454",
		"#D12E2E",
		"#A72525",
		"#7D1C1C",
		"#541212",
		"#2A0909",
	],
	orange: [
		"#FCEEE9",
		"#F5CFC1",
		"#EFB199",
		"#E99272",
		"#E3744A",
		"#DD5522",
		"#B1441B",
		"#853314",
		"#58220E",
		"#2C1107",
	],
	gray: [
		"#F2F1F3",
		"#DAD9DE",
		"#C2C0C9",
		"#AAA8B3",
		"#928F9E",
		"#7A7689",
		"#625F6D",
		"#494752",
		"#312F37",
		"#18181B",
	],
	purple: [
		"#F2F0F4",
		"#D9D6E1",
		"#C1BCCD",
		"#A9A1BA",
		"#9187A6",
		"#796D92",
		"#605775",
		"#484158",
		"#302B3B",
		"#18161D",
	],
	blue: [
		"#EDEEF7",
		"#CDCFEA",
		"#ADB0DC",
		"#8C91CE",
		"#6C72C1",
		"#4C53B3",
		"#3D428F",
		"#2D326C",
		"#1E2148",
		"#0F1124",
	],
};

export default function MyApp({ Component, pageProps }: AppProps) {
	return (
		<>
			<Head>
				<title>OverBooked</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<MantineProvider
				withNormalizeCSS
				theme={{
					headings: {
						fontFamily: "Amatic SC, sans-serif",
					},
					fontFamily: "Ubuntu, sans-serif",
					primaryColor: "red",
					primaryShade: 6,
					colors: {
						red: colors.red,
						orange: colors.orange,
						gray: colors.gray,
						violet: colors.purple,
						blue: colors.blue,
					},
					colorScheme: "dark",
				}}>
				<Component {...pageProps} />
			</MantineProvider>
		</>
	);
}
